const crosswordsTitle = 'QAE: Testing vs Debugging and Testing Principles';
const data = [
  {
    clue: '___ paradox: The same set of test cases, when repeated over time, will no longer find new defects',
    answer: 'Pesticide',
    orientation: 'down',
    x: 7,
    y: 1,
    legend: 1,
  },
  {
    clue: `Test results return no errors; therefore, it should fulfill the client's needs`,
    answer: 'misconception',
    orientation: 'across',
    x: 5,
    y: 3,
    legend: 2,
  },
  {
    clue: 'Debugging should be done ___',
    answer: 'manually',
    orientation: 'down',
    x: 17,
    y: 1,
    legend: 3,
  },
  {
    clue: 'Debugging is for ___ defects',
    answer: 'removing',
    orientation: 'down',
    x: 10,
    y: 6,
    legend: 4,
  },
  {
    clue: 'Exhaustive testing is ___',
    answer: 'impossible',
    orientation: 'across',
    x: 1,
    y: 7,
    legend: 5,
  },
  {
    clue: 'The first step in the debugging process is ___ the bug',
    answer: 'reproducing',
    orientation: 'across',
    x: 6,
    y: 9,
    legend: 6,
  },
  {
    clue: 'As much as possible, testing should be done ___',
    answer: 'automatically',
    orientation: 'across',
    x: 3,
    y: 11,
    legend: 7,
  },
  {
    clue: 'Testing is for ___ defects in the test object',
    answer: 'finding',
    orientation: 'across',
    x: 4,
    y: 13,
    legend: 8,
  },
];
